### PR TITLE
SAK-32754 - Change drop default in conversion script

### PR DESCRIPTION
**Pull request by jonespm**

### CODE REVIEW

**Comment by ern** [comment]
If this is removed it more than likely cause some issues so would like to understand exactly what the issue is first.

**Comment by jonespm** [comment]
I don't really understand, the Oracle script adds defaults (or confirms the default of null) while the MySQL script is dropping the defaults that already hibernate creates by default in the database schema. 

These "drop defaults" are also in the 12 script. I don't see us ever dropping defaults in any other conversion script.

**Comment by ern** [comment]
So in Oracle to remove the default of a column is to set it as NULL, I guess I could've used the same alter script in MySQL, but drop default as I understand its the same.
`alter table GB_GRADABLE_OBJECT_T modify IS_EXTRA_CREDIT bit(1);`

**Comment by jonespm** [comment]
What we don't understand is why and in a maintenance release. As Hendrck says in the message
"If you aren't sure this got fixed, I recommend skipping that upgrade; having a
default value which queries ideally don't use (anymore) won't hurt much."

It's also STILL THERE in the auto.ddl defaults so if you happen to start on Sakai 12 you won't get this conversion run because hibernate XML is creating it with a default. 

And it ends up with this crash because the setter doesn't seem to have a default value to set even in hibernate when it creates the default gradebook.

```
Caused by: org.springframework.dao.DataIntegrityViolationException: Hibernate
operation: could not insert: [org.sakaiproject.tool.gradebook.CourseGrade];
SQL [insert into GB_GRADABLE_OBJECT
_T (VERSION, GRADEBOOK_ID, NAME, REMOVED, SORT_ORDER, CATEGORIZED_SORT_ORDER,
OBJECT_TYPE_ID) values (?, ?, ?, ?, ?, ?, 2)]; Field 'IS_EXTRA_CREDIT' doesn't
have a default value; nested exc
eption is java.sql.SQLException: Field 'IS_EXTRA_CREDIT' doesn't have a
default value
        at
org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:
243)
        at
org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:
73)
        at
org.springframework.orm.hibernate3.HibernateAccessor.convertJdbcAccessException(HibernateAccessor.java:
426)
        at
org.springframework.orm.hibernate3.HibernateAccessor.convertHibernateAccessException(HibernateAccessor.java:
412)
        at
org.springframework.orm.hibernate3.HibernateTemplate.doExecute(HibernateTemplate.java:
415)
        at
org.springframework.orm.hibernate3.HibernateTemplate.execute(HibernateTemplate.java:
341)
        at
org.sakaiproject.component.gradebook.GradebookFrameworkServiceImpl.addGradebook(GradebookFrameworkServiceImpl.java:
73)
```

**Comment by jonespm** [comment]
Okay, I updated conversion PR

**Pull request merged**
