### PR TITLE
Update sakai_21_mysql_conversion.sql

### PR DESCRIPTION
**Pull request by csev**
Please @bjones86 - make this happen the right way in the mysterious world of Oracle

### CODE REVIEW

**Comment by bjones86** [comment]
It's the exact same in Oracle:

```
 ALTER TABLE lti_tools RENAME COLUMN allowsettings TO allowsettings_ext;
```

**Comment by mpellicer** [comment]
This is now required in 20.x, we experimented an error when upgrading to the latest 20.x

After applying the script Lessons worked again.

**Comment by mpellicer** [comment]
This should be merged into 20.2 -> 20.3 migration script.

**Review by ern — APPROVED** [review]

**Comment by ottenhoff** [comment]
Yes, what mpellicer said above. This was merged into 20.x. It's a production killer.

**Comment by bjones86** [comment]
Which SAK ticket is this for?

**Comment by ottenhoff** [comment]
`basiclti/basiclti-api/src/java/org/sakaiproject/lti/api/LTIService.java
128:            // SAK-44810 changed this from allowsettings to allowsettings_ext`

**Comment by bjones86** [comment]
Thanks. Further inquiry: why was this merged without an Oracle equivalent? I provided it in the first comment above.

**Pull request merged**
