### PR TITLE
S2U-28 Tag support for private messages

### PR DESCRIPTION
**Pull request by bgarciaentornos**

### CODE REVIEW

**Comment by bgarciaentornos** [comment]
I've added the steps to populate the existing sites, taken from existing scripts

**Comment by mpellicer** [comment]
Works fine in MySQL.

image

**Comment by mpellicer** [comment]
Works like a charm in Oracle.
image

**Review by mpellicer — APPROVED** [review]

**Comment by mpellicer** [comment]
Nice job @bgarciaentornos !

**Pull request merged**
