### PR TITLE
SAK-38427: Forums > new settings to disable email notifications at the topic level

### PR DESCRIPTION
**Pull request by bjones86**
https://jira.sakaiproject.org/browse/SAK-38427

This PR introduces two new settings at the topic level:

* Allow email notifications for new messages
* Include contents of messages in email notifications

This new feature arose out of a faculty member request, who was concerned about the security of sensitive forum data being sent in plain text via email.

Both settings default to the enabled state to preserve OOTB functionality.

### CODE REVIEW

**Comment by bjones86** [comment]
Functionality @ https://github.com/sakaiproject/sakai/pull/5524

**Comment by mpellicer** [comment]
@bjones86 I think this should be in the 13 conversion script, am I right? Or if this is gonna be merged back to 12 this may be in 12.0_12.1.

I did the same in #30

**Comment by bjones86** [comment]
Yes, good catch, I added them to the wrong files. I'll fix it up, thanks @mpellicer!

**Comment by bjones86** [comment]
@jonespm, I've moved them into the sakai_13* scripts.

**Pull request merged**
