### PR TITLE
SAK-44967 - Conversion script for the gradebook table.

### PR DESCRIPTION
**Pull request by mpellicer**
This is paired with https://github.com/sakaiproject/sakai/pull/9326

This is also paired with https://github.com/sakaiproject/sakai/pull/9382

### CODE REVIEW

**Review by bjones86 — APPROVED** [review]

**Comment by ottenhoff** [comment]
This can all be put into one column quite easily as this is quite messy. 

Is it important to ever query on these single columns (e.g., via a reporting application outside of Sakai)? 

If not, then one column with 101010101 would represent settings quite well

**Comment by ottenhoff** [comment]
At the same time, I hated the effort of jamming everything into XML blobs. My fear here is that there is an endless amount of additional flags that will be needed for this feature.

**Comment by jesusmmp** [comment]
Please, change oracle script:

ALTER TABLE gb_gradebook_t ADD allow_compare_grades NUMBER(1,0) DEFAULT 0 NOT NULL ;
ALTER TABLE gb_gradebook_t ADD comparing_display_grades NUMBER(1,0) DEFAULT 0 NOT NULL;
ALTER TABLE gb_gradebook_t ADD comparing_display_firstnames NUMBER(1,0) DEFAULT 0 NOT NULL;
ALTER TABLE gb_gradebook_t ADD comparing_display_surnames NUMBER(1,0) DEFAULT 0 NOT NULL;
ALTER TABLE gb_gradebook_t ADD comparing_display_teachcomment NUMBER(1,0) DEFAULT 0 NOT NULL;
ALTER TABLE gb_gradebook_t ADD comparing_display_allgradeitem NUMBER(1,0) DEFAULT 0 NOT NULL;
ALTER TABLE gb_gradebook_t ADD comparing_randomizedata NUMBER(1,0) DEFAULT 0 NOT NULL;

NOT NULL should be at the end.

**Comment by mpellicer** [comment]
> Please, change oracle script:
> 
> ALTER TABLE gb_gradebook_t ADD allow_compare_grades NUMBER(1,0) DEFAULT 0 NOT NULL ;
> ALTER TABLE gb_gradebook_t ADD comparing_display_grades NUMBER(1,0) DEFAULT 0 NOT NULL;
> ALTER TABLE gb_gradebook_t ADD comparing_display_firstnames NUMBER(1,0) DEFAULT 0 NOT NULL;
> ALTER TABLE gb_gradebook_t ADD comparing_display_surnames NUMBER(1,0) DEFAULT 0 NOT NULL;
> ALTER TABLE gb_gradebook_t ADD comparing_display_teachcomment NUMBER(1,0) DEFAULT 0 NOT NULL;
> ALTER TABLE gb_gradebook_t ADD comparing_display_allgradeitems NUMBER(1,0) DEFAULT 0 NOT NULL;
> ALTER TABLE gb_gradebook_t ADD comparing_randomizedata NUMBER(1,0) DEFAULT 0 NOT NULL;
> 
> NOT NULL should be at the end.

I don't see why we should include NOT NULL at the end, but it's fine.

**Comment by jesusmmp** [comment]
@mpellicer, on ORACLE these columns:

- comparing_display_teachcomments
- comparing_display_allgradeitems 

exceed 30 size and we have an error.

We should change these column names (for example) :
- comparing_display_teachcomment
- comparing_display_allgradeitem

and the respectives changes on the code...

**Comment by bjones86** [comment]
> @mpellicer, on ORACLE these columns:
> 
>     * comparing_display_teachcomments
> 
>     * comparing_display_allgradeitems
> 
> 
> exceed 30 size and we have an error.

Thanks for pointing this out. I always forget about the 30 character name limit in Oracle...

**Review by bjones86 — CHANGES_REQUESTED** [review]
Oracle names are required to be 30 characters or less.

**Review by bjones86 — APPROVED** [review]

**Pull request merged**
