### PR TITLE
Create sakai_20_3-20_4_oracle_conversion.sql

### PR DESCRIPTION
**Pull request by csev**
Could @bjones86 take a look - should the BLOB be null allowed too?

### CODE REVIEW

**Comment by csev** [comment]
The purpose of the field is to hold a text representation of a PKI public key - usually about 1000 characters - in MySQL it would be MEDIUMTEXT

**Comment by csev** [comment]
Actually if you look at when the other keys were added in sakai_19_oracle_conversion.sql - it looks like they were added as (lti13_tool_public CLOB) - apparently it is OK for CLOBS to be null

**Comment by bjones86** [comment]
If you can guarantee that the value will never exceed 4000 characters, then you can use the `VARCHAR2(4000)` datatype. If you're using a multi-byte charset that may come close to 4000 characters, then it's better to use `CLOB`

**Comment by csev** [comment]
I am 99.99% sure it will never exceed 4000 characters :)

**Comment by bjones86** [comment]
Okay cool, in that case I would recommend using `VARCHAR2` as it's much nicer to work with in the Oracle world.

**Comment by csev** [comment]
All the other fields managed by FOORM are CLOB - and if autoddl runs at the beginning it will be a CLOB because FOORM does that.  So it is better to be CLOB even with imperfections.  We will never use a LIKE or add an index for this.

**Comment by bjones86** [comment]
Sounds appropriate

**Pull request merged**
