### PR TITLE
S2U-42 Roster: The Card Game!

### PR DESCRIPTION
**Pull request by stetsche**
Conversion script for PR: https://github.com/sakaiproject/sakai/pull/11424

### CODE REVIEW

**Comment by mpellicer** [comment]
MySQL script created with a warning, I think we should correct it:

image

**Comment by mpellicer** [comment]
The Oracle script fails:

image

**Comment by mpellicer** [comment]
Oracle script fixed:

image

**Comment by mpellicer** [comment]
@stetsche Could you check my changes against your source? Thanks!

**Comment by stetsche** [comment]
Nice, thanks for testing fixing it @mpellicer!

**Comment by stetsche** [comment]
I changed the id part, because of the change to uuid. I tested the mysql script locally.

**Review by mpellicer — APPROVED** [review]

**Pull request merged**
