### PR TITLE
Create sakai_21_0-21_1_oracle_conversion.sql

### PR DESCRIPTION
**Pull request by csev**
Could @bjones86 take a look - should the BLOB be null allowed too?

### CODE REVIEW

**Comment by bjones86** [comment]
I think it's probably fine, but I'm not exactly sure of the purpose of this field. If you think that it shouldn't be nullable I would change it to something like this:

```
ALTER TABLE lti_tools ADD lti13_platform_public_old BLOB NOT NULL DEFAULT empty_blob();
```

**Comment by csev** [comment]
The purpose of the field is to hold a text representation of a PKI public key - usually about 1000 characters - in MySQL it would be MEDIUMTEXT

**Comment by csev** [comment]
Actually if you look at when the other keys were added in sakai_19_oracle_conversion.sql - it looks like they were added as (lti13_tool_public CLOB) - apparently it is OK for CLOBS to be null

**Comment by bjones86** [comment]
If you can guarantee that the value will never exceed 4000 characters, then you can use the `VARCHAR2(4000)` datatype. If you're using a multi-byte charset that may come close to 4000 characters, then it's better to use `CLOB`

**Pull request merged**
